FROM python:3.6.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Creating lockkliye_restapi workspace
RUN mkdir /lockkliye_restapi
WORKDIR /lockkliye_restapi

# Updating internal debian to newest version
RUN apt-get update -y
RUN apt-get install -y netcat

COPY requirements.txt /lockkliye_restapi/

# Installing python-dependencies
RUN pip install -r requirements.txt

# Copy source code over
COPY . /lockkliye_restapi/

ENTRYPOINT ["/lockkliye_restapi/entrypoint.dev.sh"]