version: '3.7'

services:
    db:
        container_name: db
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=postgres_db
        image: postgres
        networks:
            - lockkliye_local
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    lockkliye_restapi:
        build:
            context: .
            dockerfile: Dockerfile.dev
            network: host
        command: python manage.py runserver 0.0.0.0:8000
        container_name: lockkliye_restapi
        depends_on:
            - db
        env_file:
            - ./.env
            - ./.env.dev
        image: lockkliye_restapi
        networks:
            - lockkliye_local
        ports:
            - 8080:8000
        volumes:
            - .:/lockkliye_restapi

networks:
    lockkliye_local:
        driver: bridge
        external: true
        name: lockkliye_local

volumes:
    postgres_data:
