# Generated by Django 3.0.2 on 2020-02-08 19:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=6, unique=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('labels', models.ManyToManyField(related_name='noteLabels', to='notes.Label')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('labels', models.ManyToManyField(related_name='listLabels', to='notes.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('lists', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='notes.List')),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.Note')),
                ('subfolders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='notes.Folder')),
            ],
        ),
    ]
